#114 Расположение temp, bls-ls-cfg + ошибки для выделенного кода.
infostart-hub/snegopat pull request #115
Opened 2020-12-13 14:09 UTC by BProg-Gladkov

реализация  #114

сделанные изменения
1. Добавлена возможность указать путь к каталогу temp.
2. Добавлена возможность указать путь к конфигурационному файлу.
3. Если выделено более чем одна строка кода отображаются ошибки только для выделенных строк кода.

@infostart-hub/snegopat - просьба прокомментировать и проверить

2020-12-16 06:19 UTC, BProg-Gladkov commented
Исправлен выбор каталога временных фалов.

2020-12-19 15:07 UTC, artbear requested changes
Замечательные доработки.
У меня есть небольшие замечания.
Посмотришь? исправишь?

2020-12-19 15:07 UTC, artbear commented on addins/bsl_analyze.js
> +    formSettings.pathToBslServer = pathToBslServer;
я правильно понимаю, что ты поменял имя реквизита на форме..

пожалуйста, выложи исходники внешней epf-файла `addins/bsl_analyze.epf`
в формате Конфигуратора в каталог `addins\src\bsl_analyze`

тогда будет проще разбирать код и понимать изменения

2020-12-19 15:07 UTC, artbear commented on addins/bsl_analyze.js
> +    sel.Title = "Укажите расположение файла Bsl_ls_cfg.json";
вот сюда бы добавить текущее значение параметра для удобства использования

иначе каждый раз придется с нуля выбирать.

2020-12-19 15:07 UTC, artbear commented on addins/bsl_analyze.js
> +    sel.Title = "Укажите расположение папки для временных файлов";
ну и сюда бы добавить текущее значение параметра для удобства использования

2020-12-19 15:12 UTC, nixel2007 commented on addins/bsl_analyze.js
> +    sel.Title = "Укажите расположение файла Bsl_ls_cfg.json";
И хорошо бы назвать файл по соглашению:
`.bsl-language-server.json`

2020-12-19 16:40 UTC, BProg-Gladkov commented on addins/bsl_analyze.js
> +var pflPathToBslServer = pflFolder + "pathToBslServer";
ок

2020-12-19 18:37 UTC, BProg-Gladkov commented on addins/bsl_analyze.js
> +    sel.Title = "Укажите расположение файла Bsl_ls_cfg.json";
ок

2020-12-19 18:37 UTC, BProg-Gladkov commented on addins/bsl_analyze.js
> +    sel.Title = "Укажите расположение папки для временных файлов";
ок

2020-12-20 19:11 UTC, BProg-Gladkov commented on addins/bsl_analyze.js
> +    formSettings.pathToBslServer = pathToBslServer;
1. Имя реквизита на форме менял.
2. Исходники выложил.

Только выкладывание исходников обработки смотрится странно:
1. Выложены исходники только по одной обработке.
2. Теперь есть обработка и исходники. 
Если кто-то обновит исходники и не обновит обработку (или наоборот), то будет не понятно что является актуальным.

2020-12-21 07:48 UTC, artbear requested changes
нашлась ошибка переименования

2020-12-21 07:48 UTC, artbear commented on addins/bsl_analyze.js
> +var pathToBslServer;
@BProg-Gladkov ты поменял имя переменной, но не исправил метод, в котором она юзается.

tryFindPathToBsl использует эту переменную

и будет ошибка при использовании этого метода.

2020-12-21 08:14 UTC, BProg-Gladkov commented on addins/bsl_analyze.js
> +var pathToBslServer;
Исправил

2020-12-21 08:35 UTC, nixel2007 commented on addins/bsl_analyze.js
> +    sel.Title = "Укажите расположение файла Bsl_ls_cfg.json";
точка в имени файла потерялась

2020-12-21 08:41 UTC, BProg-Gladkov commented on addins/bsl_analyze.js
> +    sel.Title = "Укажите расположение файла Bsl_ls_cfg.json";
А зачем точка перед именем файла?
Есть какое-то соглашение?

2020-12-21 08:55 UTC, nixel2007 commented on addins/bsl_analyze.js
> +    sel.Title = "Укажите расположение файла Bsl_ls_cfg.json";
Именно по такому имени файла (с точкой) сам бсл лс ищет конфиг в рабочем каталоге + при редактировании такого файла в VSCode с установленным bsl-плагином будет работать автодополнение по json-schema.

2020-12-21 09:14 UTC, BProg-Gladkov commented on addins/bsl_analyze.js
> +    sel.Title = "Укажите расположение файла Bsl_ls_cfg.json";
Исправил

2021-01-20 07:52 UTC, artbear requested changes
Похоже. последний вопрос остался и все.
и смержим уже этот неожиданный долгострой )

2021-01-20 07:52 UTC, artbear commented on addins/bsl_analyze.js
> +        var tmpPath = pathToTemp + "bsl\\";
Еще одну проблему увидел.

Код раньше юзал уникальную папку для каждого запущенного экземпляра Конфигуратора.

А твой код юзает одну и ту же папку ВремПапка\bsl для всех запущенных Снегопатов\Конфигураторов.
Если вдруг захотим сделать 2 анализа в соседних Конфигураторах и они быстро не выполнятся, будут проблемы.

Насколько ты считаешь важным наличие одной общей папки для анализа?
ИМХО проще с отдельными папками, как в текущем коде.

2021-01-20 07:56 UTC, artbear commented on addins/bsl_analyze.js
> +    sel.Title = "Укажите расположение файла Bsl_ls_cfg.json";
@BProg-Gladkov Ты имя неточно исправил, я еще слегка поправил.

2021-01-20 18:57 UTC, BProg-Gladkov commented on addins/bsl_analyze.js
> +        var tmpPath = pathToTemp + "bsl\\";
Я за все это время ни одного разу на запустил две проверки одновременно и не представляю зачем это может быть нужно.
Если это кажется критичным - можно всегда генерировать случайное имя каталога в bsl и уже в него писать "text.bsl".

2021-02-01 08:33 UTC, artbear commented on addins/bsl_analyze.js
> +        var tmpPath = pathToTemp + "bsl\\";
@BProg-Gladkov да. предлагаю сделать случайное имя каталога

и смержим уже этог ПР )

2021-02-02 08:06 UTC, artbear commented on addins/src/bsl_analyze/bsl_analyze/Templates/TypeScriptSource/Ext/Template.txt
> +﻿//engine: JScript
напомни, зачем этот макет-дубль кода нужен ?

2021-02-02 08:43 UTC, BProg-Gladkov commented on addins/src/bsl_analyze/bsl_analyze/Templates/TypeScriptSource/Ext/Template.txt
> +﻿//engine: JScript
В обработке были вложены макеты. Я пробовал понять зачем они, но так и не понял.
Хотел удалить - но потом решил, что удалять непонятное для новенького в проекте - так себе идея

2021-02-03 07:17 UTC, artbear commented
В последнем коммите почему-то удален файл addins/bsl_analyze.epf (

и файл Form.bin

верни, их, пожалуйста, они нужны

2021-02-03 07:50 UTC, BProg-Gladkov commented
Не понял что надо исправить.
Вроде все на месте:
![image](https://user-images.githubusercontent.com/33430119/106714996-a4c64f80-660d-11eb-9e4a-283ede1a096a.png)

2021-02-03 08:07 UTC, merged

2021-02-03 08:09 UTC, artbear commented
УРА! Долгострой закрыли )

@BProg-Gladkov Тебе большое спасибо за терпение!

И поздравляю с первым ПР в проекте!

Больше, больше контрибьюторов! )