Правки по 2 ISSUES
infostart-hub/snegopat pull request #144
Opened 2021-02-07 21:17 UTC by 7OH

Правки по #126 и #140

реализация  #

По #140 добавлены галки для включения или отключения отбора по метаданным.
А так же само поле, которое работает почти также как в скрипте "Навигатор по метаданным"

По #126 добавлена галка "Вертикальное окно" в настройки основного окна.
Сделать одной формой не вышло, так как платформа не даёт менять вид прикрепления окна на ходу.
Сделано двумя формами, которые и открываются в зависимости от галки.
В работе есть один нюанс - менять настройку на ходу можно, но перестают работать кнопки на панели задач.
Может @orefkov сможет что-то позже придумать, но пока на этом месте стоит try\catch
https://github.com/infostart-hub/snegopat/blob/d9c12f4f1a27321591d1b25233473908ce8e7ebc/addins/Libs/ScriptForm.js#L270
Сделал выбор основной формы при первой инициализации по настройке - так работает.
В общем определились как больше нравится и не меняем.
Или после изменения - перезайти.

Проверено на релизе 8.3.17.1851

@infostart-hub/snegopat - предлагаю прокомментировать и проверить

2021-02-08 09:27 UTC, artbear commented
@7OH странные результаты
![image](https://user-images.githubusercontent.com/2920817/107200550-e3db1300-6a08-11eb-8c05-f68f4b503b1f.png)

2021-02-08 09:35 UTC, artbear requested changes
есть непонятности
ответишь?

2021-02-08 09:35 UTC, artbear commented on addins/extSearchReplace.js
> +	//доделать определение текущего метаданного
в таких местах, где нужно что-то доделать, общепринятая практика - ставить TODO или FIXME в начале комментария

2021-02-08 09:35 UTC, artbear commented on addins/extSearchReplace.js
> +		//"Константа Константа1: МодульМенеджераЗначения"
отладочные сообщения лучше убрать.

2021-02-08 09:35 UTC, artbear commented on addins/extSearchReplace.js
> +			var index = testString.indexOf(filters[s])
ошибка? в s уже значение, а в коде еще идет обращение внутри поиска indexOf(filters[s]) ?

2021-02-08 09:43 UTC, 7OH commented on addins/extSearchReplace.js
> +	//доделать определение текущего метаданного
Вынес комментарий в TODO

2021-02-08 09:43 UTC, 7OH commented on addins/extSearchReplace.js
> +		//"Константа Константа1: МодульМенеджераЗначения"
Убрал

2021-02-08 09:43 UTC, 7OH commented on addins/extSearchReplace.js
> +			var index = testString.indexOf(filters[s])
Не ошибка.
![изображение](https://user-images.githubusercontent.com/3063507/107202461-e76b9b80-6a02-11eb-8dd0-d6e89be4f959.png)

2021-02-08 10:08 UTC, artbear commented on addins/extSearchReplace.js
> +			for(var s in filtersToUpdate)
использование for ( in ) не рекомендуется (

https://stackoverflow.com/questions/500504/why-is-using-for-in-for-array-iteration-a-bad-idea

2021-02-08 10:08 UTC, artbear commented on addins/extSearchReplace.js
> +			var index = testString.indexOf(filters[s])
использование for ( in ) не рекомендуется (

https://stackoverflow.com/questions/500504/why-is-using-for-in-for-array-iteration-a-bad-idea

2021-02-08 11:08 UTC, 7OH commented on addins/extSearchReplace.js
> +			var index = testString.indexOf(filters[s])
Заменил

2021-02-08 11:08 UTC, 7OH commented on addins/extSearchReplace.js
> +			for(var s in filtersToUpdate)
Заменил

2021-02-08 11:43 UTC, artbear commented on addins/extSearchReplace.js
> +		for(var s = 0; s <= filters.length - 1; s ++)
1 s - непривычное имя для индекса )
обычно все-таки i или idx или index

2 проще и нагляднее `s < filters.length` вместо `s <= filters.length - 1`, да?

2021-02-08 11:44 UTC, artbear commented on addins/extSearchReplace.js
> +			for(var s = 0; s <= filtersToUpdate.length - 1; s ++)
и здесь также - и имя индекса, и знак <=

2021-02-08 12:05 UTC, 7OH commented on addins/extSearchReplace.js
> +		for(var s = 0; s <= filters.length - 1; s ++)
Готово

2021-02-08 12:05 UTC, 7OH commented on addins/extSearchReplace.js
> +			for(var s = 0; s <= filtersToUpdate.length - 1; s ++)
Готово

2021-02-13 10:47 UTC, 7OH commented
Пробовал поиск на нашей ЕРП.
Текст в задаче был (последний же элемент в дереве).
Без фильтра - 7 минут.
С фильтром - 10 секунд.

2021-02-23 13:25 UTC, artbear commented
@kuntashov можешь проверить поведение? у меня были странные проблемы с этим скриптом (
сейчас вроде работает, но осадочек остался )

2021-02-23 13:26 UTC, artbear commented
для больших конфигураций добавленный нами фильтр очень полезен.

хочется побыстрее внедрить в работу.

@kuntashov может быть, интерфейсные фишки подскажешь, чтобы улучшить

2021-08-21 07:03 UTC, artbear commented
ПР из ядерного Снегопата https://github.com/infostart-hub/snegopat_modul/pull/21

2021-08-21 07:03 UTC, merged