Выравнивание по последней запятой
infostart-hub/snegopat pull request #149
Opened 2021-02-17 15:40 UTC by 7OH

Вынес функцию по запятым в отдельную и добавил параметр, чтобы дублировать код.

реализация  #

По переданному параметру в нужном месте ищем первую или последнюю запятую.

-
-

Проверено на релизе 8.3.17.1989

@infostart-hub/snegopat - предлагаю прокомментировать и проверить

2021-02-21 11:03 UTC, artbear requested changes

2021-02-21 11:03 UTC, artbear commented on addins/format.js
> +function AlignByComa(byFirst) {
Опечатка вместо Comma

я попробовал было сам сразу на Гитхабе поправить, но выдается ошибка 404 при попытке коммита (

так что исправь сам, пожалуйста.

2021-02-21 12:33 UTC, 7OH commented on addins/format.js
> +function AlignByComa(byFirst) {
Готово

2021-02-23 13:23 UTC, artbear approved these changes

2021-02-23 13:24 UTC, merged