Поиск и замена
infostart-hub/snegopat pull request #71
Opened 2020-10-18 20:16 UTC by 7OH

dynwrapx.dll вроде нигде не используется больше. Предлагаю удалить, дабы не напрягать антивирус зря.
Формы скрипта поиска перенесены во внешнюю обработку.
Добавлена возможность замены, а также поиска по "НаКлиенте\НаСервере".

реализация  #

сделанные изменения

-
-

@infostart-hub/snegopat - просьба прокомментировать и проверить

2020-10-18 20:22 UTC, artbear requested changes
по диагонали просмотрел.

самое главное - куча авторских комментариев. нужно от них избавиться.

2020-10-18 20:22 UTC, artbear commented on addins/extSearch.js
> +	//Павлюков - переиначил логику работы с RegExpEditor
Авторские комментарии лучше удалить.

`//Павлюков - ` заменить на `// `

2020-10-18 20:22 UTC, artbear commented on addins/extSearch.js
> +		this.form.КлючСохраненияПоложенияОкна = "extSearchReplace.dialog.js"
здесь важно, что скрипт пока называется по-старому extSearchReplace.js ?

2020-10-18 20:22 UTC, artbear commented on addins/extSearch.js
> +		this.form.КлючСохраненияПоложенияОкна = "extSearchReplace.js"
возможно, и здесь переименование требуется?

2020-10-18 20:22 UTC, artbear commented on addins/extSearch.js
> +	//Павлюков
убрать и такие авторские комментарии `//Павлюков`

2020-10-19 20:00 UTC, merged

2020-10-19 20:04 UTC, artbear commented
@7OH Добавил переименование скрипта и епф-файла в extSearchReplace

2020-10-19 20:06 UTC, 7OH commented on addins/extSearch.js
> +		this.form.КлючСохраненияПоложенияОкна = "extSearchReplace.js"
Не - ключом настроек может быть что угодно - как в самой 1С при сохранении настроек.