Расширения
infostart-hub/snegopat pull request #94
Opened 2020-11-11 23:00 UTC by 7OH

Доработан скрипт для https://github.com/infostart-hub/snegopat/issues/93.
Перед тестированием необходимо сбросить сохраненные данные скрипта.
Плюс поправлен вылет, если диалог, на который хук поставлен не содержит view.

реализация  #

Настройки сохраняются в соответствие с именами расширений.
Немного изменил логику отлова диалогов - окна расширений перед показом имеют старый заголовок, пришлось ловить перед открытием.

@infostart-hub/snegopat - просьба прокомментировать и проверить

2020-11-12 21:42 UTC, kuntashov commented
> Перед тестированием необходимо сбросить сохраненные данные скрипта.

@7OH а это можно сделать как-то автоматически?
Что произойдет, если не сбросить настройки?

2020-11-12 23:09 UTC, 7OH commented
Добавил автоконвертацию при старте и сообщение об этом действии.

2020-11-13 08:38 UTC, artbear requested changes
есть небольшие замечания

2020-11-13 08:38 UTC, artbear commented on addins/stg_autoconnect.js
> +        repoType = (matches[2]=="конфигурации")?1:2;
а почему не true\false, а какие-то магические числа 1 и 2?
все равно юзаются только 2 значения

предлагаю улучшить код
1 предлагаю эту переменную сделать локальной внутри блока  `if (matches && matches.length)`
2 убрать условие в строке 64 `if(repoType)` и вставить в блок выше

ну и не такое обязательное
3 в идеале бы весь код обработки подключения расширения вынести бы в отдельную функцию
чтобы основной код метода-перехватчика модального окна не превращался в длиннущую портянку

2020-11-13 09:04 UTC, 7OH commented on addins/stg_autoconnect.js
> +        repoType = (matches[2]=="конфигурации")?1:2;
Я на будущее оставил. Вдруг чего ещё добавят с хранилищем )

2020-11-13 09:20 UTC, artbear commented on addins/stg_autoconnect.js
> +        repoType = (matches[2]=="конфигурации")?1:2;
код на будущее зло.
делай простой и понятный код, легче будет сопровождать и дорабатывать.

сделаешь мои предложения 1, 2 или нет?
если сильно не хочется, могу и так принять
но лучше бы исправить - принцип бойскаута - код постепенно делаем лучше )

2020-11-13 09:21 UTC, artbear commented on addins/stg_autoconnect.js
> +        repoType = (matches[2]=="конфигурации")?1:2;
ага, вижу, что ты исправил.
отлично.
стало лучше

2020-11-13 09:22 UTC, 7OH commented on addins/stg_autoconnect.js
> +        repoType = (matches[2]=="конфигурации")?1:2;
Поправил вроде уже. Изменения закинул по всем то пунктам.

2020-11-13 09:27 UTC, artbear reviewed
для обсуждения

2020-11-13 09:27 UTC, artbear commented on addins/stg_autoconnect.js
> +		doAutoConnect(dlgInfo, matches);
1 и назвал бы этот метод doAutoConnectToStorage )
2 я бы вот эту проверка на окно хранилища перенес бы внутрь метода doAutoConnectToStorage 

чтобы внутренности этого метода не выносить наружу, а оставить внутри метода

API этого метода
- проверяет наличие окна подключения к хранилищу
- если не это окно, возвращает false
- если это окно, делает попытку подключения и возвращает true

тогда начальный код в onDoModal был бы простой
```js
if(doAutoConnectToStorage((dlgInfo)){
  return
}
```

2020-11-13 09:29 UTC, 7OH commented on addins/stg_autoconnect.js
> +		doAutoConnect(dlgInfo, matches);
Сейчас переделаю.

2020-11-13 10:25 UTC, merged

2020-11-13 10:26 UTC, artbear commented
@7OH очередной твой ПР принят! Круто, ты сейчас самый активный разработчик скриптов!